apiVersion: v1
kind: Service
metadata:
  name: app-navigator
  namespace: atriarch-utilities
  labels:
    app: app-navigator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: app-navigator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-navigator
  namespace: atriarch-utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-navigator
  template:
    metadata:
      labels:
        app: app-navigator
    spec:
      containers:
      - image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        name: app-navigator
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: atriarch-systems-docker-group
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-navigator
  namespace: atriarch-utilities
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-navigator
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-navigator
  namespace: atriarch-utilities
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app-navigator.atriarch.systems
    http:
      paths:
      - path: /
        backend:
          serviceName: app-navigator
          servicePort: http
